name: my-namespace/example-http
title: Example HTTP Server
description: Example HTTP server package with FX integration and middleware support
type: fx-module
version: v1.0.0
author: Your Name
license: MIT
repository: https://github.com/your-username/my-namespace
website: https://your-namespace-docs.com
destination: internal/adapter/my-namespace/example-http
tags:
  - transport
  - http
  - example
capabilities:
  - http-server
  - middleware
  - routing
